export const indexSql = `
CREATE INDEX IF NOT EXISTS "idx_task_company" ON "Task"("company");
CREATE INDEX IF NOT EXISTS "idx_task_company_updated" ON "Task"("company", "updatedAt");
CREATE INDEX IF NOT EXISTS "idx_task_company_status" ON "Task"("company", "status");
CREATE INDEX IF NOT EXISTS "idx_task_company_project" ON "Task"("company", "project");
CREATE INDEX IF NOT EXISTS "idx_task_company_sprint" ON "Task"("company", "sprintId");
CREATE INDEX IF NOT EXISTS "idx_task_project_active_updated" ON "Task"("project", "updatedAt" DESC) WHERE "deletedAt" IS NULL;
CREATE INDEX IF NOT EXISTS "idx_task_company_active_updated" ON "Task"("company", "updatedAt" DESC) WHERE "deletedAt" IS NULL;
CREATE INDEX IF NOT EXISTS "idx_task_company_active_status_updated" ON "Task"("company", "status", "updatedAt" DESC) WHERE "deletedAt" IS NULL;
CREATE INDEX IF NOT EXISTS "idx_task_status" ON "Task"("status");
CREATE INDEX IF NOT EXISTS "idx_task_assignee" ON "Task"("assignee");
CREATE INDEX IF NOT EXISTS "idx_bug_company" ON "Bug"("company");
CREATE INDEX IF NOT EXISTS "idx_bug_company_updated" ON "Bug"("company", "updatedAt");
CREATE INDEX IF NOT EXISTS "idx_bug_company_status" ON "Bug"("company", "status");
CREATE INDEX IF NOT EXISTS "idx_bug_company_project" ON "Bug"("company", "project");
CREATE INDEX IF NOT EXISTS "idx_bug_company_module" ON "Bug"("company", "module");
CREATE INDEX IF NOT EXISTS "idx_bug_company_sprint" ON "Bug"("company", "sprintId");
CREATE INDEX IF NOT EXISTS "idx_bug_project_active_created" ON "Bug"("project", "createdAt" DESC) WHERE "deletedAt" IS NULL;
CREATE INDEX IF NOT EXISTS "idx_bug_company_active_updated" ON "Bug"("company", "updatedAt" DESC) WHERE "deletedAt" IS NULL;
CREATE INDEX IF NOT EXISTS "idx_bug_company_active_created" ON "Bug"("company", "createdAt" DESC) WHERE "deletedAt" IS NULL;
CREATE INDEX IF NOT EXISTS "idx_bug_company_active_status_updated" ON "Bug"("company", "status", "updatedAt" DESC) WHERE "deletedAt" IS NULL;
CREATE INDEX IF NOT EXISTS "idx_bug_status" ON "Bug"("status");
CREATE INDEX IF NOT EXISTS "idx_bug_suggesteddev" ON "Bug"("suggestedDev");
CREATE INDEX IF NOT EXISTS "idx_testcase_company" ON "TestCase"("company");
CREATE INDEX IF NOT EXISTS "idx_testcase_company_updated" ON "TestCase"("company", "updatedAt");
CREATE INDEX IF NOT EXISTS "idx_testcase_company_status" ON "TestCase"("company", "status");
CREATE INDEX IF NOT EXISTS "idx_testcase_company_suite" ON "TestCase"("company", "testSuiteId");
CREATE INDEX IF NOT EXISTS "idx_testcase_company_active_suite" ON "TestCase"("company", "testSuiteId", "id") WHERE "deletedAt" IS NULL;
CREATE INDEX IF NOT EXISTS "idx_testcase_assignee" ON "TestCase"("assignee");
CREATE INDEX IF NOT EXISTS "idx_testcase_status" ON "TestCase"("status");
CREATE INDEX IF NOT EXISTS "idx_testcase_suite" ON "TestCase"("testSuiteId");
CREATE INDEX IF NOT EXISTS "idx_testplan_company" ON "TestPlan"("company");
CREATE INDEX IF NOT EXISTS "idx_testplan_company_updated" ON "TestPlan"("company", "updatedAt");
CREATE INDEX IF NOT EXISTS "idx_testplan_company_project" ON "TestPlan"("company", "project");
CREATE INDEX IF NOT EXISTS "idx_testplan_project_active_updated" ON "TestPlan"("project", "updatedAt" DESC) WHERE "deletedAt" IS NULL;
CREATE INDEX IF NOT EXISTS "idx_testplan_company_sprint" ON "TestPlan"("company", "sprint");
CREATE INDEX IF NOT EXISTS "idx_testplan_company_status" ON "TestPlan"("company", "status");
CREATE INDEX IF NOT EXISTS "idx_testplan_company_endDate" ON "TestPlan"("company", "endDate");
CREATE INDEX IF NOT EXISTS "idx_testplan_company_token" ON "TestPlan"("company", "publicToken");
CREATE INDEX IF NOT EXISTS "idx_testplan_company_active_updated" ON "TestPlan"("company", "updatedAt" DESC) WHERE "deletedAt" IS NULL;
CREATE INDEX IF NOT EXISTS "idx_testplan_company_active_sprint" ON "TestPlan"("company", "sprint", "updatedAt" DESC) WHERE "deletedAt" IS NULL;
CREATE INDEX IF NOT EXISTS "idx_testsuite_company" ON "TestSuite"("company");
CREATE INDEX IF NOT EXISTS "idx_testsuite_company_updated" ON "TestSuite"("company", "updatedAt");
CREATE INDEX IF NOT EXISTS "idx_testsuite_company_plan" ON "TestSuite"("company", "testPlanId");
CREATE INDEX IF NOT EXISTS "idx_testsuite_company_status" ON "TestSuite"("company", "status");
CREATE INDEX IF NOT EXISTS "idx_testsuite_assignee" ON "TestSuite"("assignee");
CREATE INDEX IF NOT EXISTS "idx_testsuite_company_token" ON "TestSuite"("company", "publicToken");
CREATE INDEX IF NOT EXISTS "idx_testsuite_plan_active_updated" ON "TestSuite"("testPlanId", "updatedAt" DESC) WHERE "deletedAt" IS NULL;
CREATE INDEX IF NOT EXISTS "idx_testsuite_company_active_plan_updated" ON "TestSuite"("company", "testPlanId", "updatedAt" DESC) WHERE "deletedAt" IS NULL;
CREATE INDEX IF NOT EXISTS "idx_activitylog_company" ON "ActivityLog"("company");
CREATE INDEX IF NOT EXISTS "idx_activitylog_company_created" ON "ActivityLog"("company", "createdAt");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_searchtoken_unique" ON "SearchToken"("company", "entityType", "entityId", "token");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_searchtoken_lookup" ON "SearchToken"("company", "entityType", "entityIdInt", "token");
CREATE INDEX IF NOT EXISTS "idx_searchtoken_company_token" ON "SearchToken"("company", "entityType", "token");
CREATE INDEX IF NOT EXISTS "idx_sprint_company" ON "Sprint"("company");
CREATE INDEX IF NOT EXISTS "idx_sprint_company_updated" ON "Sprint"("company", "updatedAt");
CREATE INDEX IF NOT EXISTS "idx_sprint_company_name" ON "Sprint"("company", "name");
CREATE INDEX IF NOT EXISTS "idx_sprint_company_status" ON "Sprint"("company", "status");
CREATE INDEX IF NOT EXISTS "idx_sprint_company_start" ON "Sprint"("company", "startDate");
CREATE INDEX IF NOT EXISTS "idx_sprint_company_endDate" ON "Sprint"("company", "endDate");
CREATE INDEX IF NOT EXISTS "idx_sprint_name_active_start" ON "Sprint"("name", "startDate" DESC) WHERE "deletedAt" IS NULL;
CREATE INDEX IF NOT EXISTS "idx_sprint_company_active_start" ON "Sprint"("company", "startDate" DESC) WHERE "deletedAt" IS NULL;
CREATE INDEX IF NOT EXISTS "idx_testcase_company_token" ON "TestCase"("company", "publicToken");
CREATE INDEX IF NOT EXISTS "idx_testsession_company_scope_date" ON "TestSession"("company", "scope", "date");
CREATE INDEX IF NOT EXISTS "idx_testsession_scope_active_date" ON "TestSession"("scope", "date" DESC) WHERE "deletedAt" IS NULL;
CREATE INDEX IF NOT EXISTS "idx_testsession_company_active_scope_date" ON "TestSession"("company", "scope", "date" DESC) WHERE "deletedAt" IS NULL;
CREATE INDEX IF NOT EXISTS "idx_meetingnote_company_updated" ON "MeetingNote"("company", "updatedAt");
CREATE INDEX IF NOT EXISTS "idx_meetingnote_company_date" ON "MeetingNote"("company", "date");
CREATE INDEX IF NOT EXISTS "idx_meetingnote_company_token" ON "MeetingNote"("company", "publicToken");
CREATE INDEX IF NOT EXISTS "idx_meetingnote_company_project" ON "MeetingNote"("company", "project");
CREATE INDEX IF NOT EXISTS "idx_meetingnote_project_active_date" ON "MeetingNote"("project", "date" DESC, "updatedAt" DESC) WHERE "deletedAt" IS NULL;
CREATE INDEX IF NOT EXISTS "idx_meetingnote_company_active_date" ON "MeetingNote"("company", "date" DESC, "updatedAt" DESC) WHERE "deletedAt" IS NULL;
CREATE INDEX IF NOT EXISTS "idx_activitylog_company_created" ON "ActivityLog"("company", "createdAt");
CREATE INDEX IF NOT EXISTS "idx_invite_company" ON "Invite"("company");
CREATE INDEX IF NOT EXISTS "idx_invite_token" ON "Invite"("token");
CREATE INDEX IF NOT EXISTS "idx_invite_company_status" ON "Invite"("company", "status");
CREATE INDEX IF NOT EXISTS "idx_user_company_active_created" ON "User"("company", "createdAt" DESC) WHERE "deletedAt" IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS "idx_assignee_userId" ON "Assignee"("userId") WHERE "userId" IS NOT NULL;
CREATE INDEX IF NOT EXISTS "idx_assignee_company_updated" ON "Assignee"("company", "updatedAt");
CREATE INDEX IF NOT EXISTS "idx_assignee_company_name" ON "Assignee"("company", "name");
CREATE INDEX IF NOT EXISTS "idx_assignee_company_status" ON "Assignee"("company", "status");
CREATE INDEX IF NOT EXISTS "idx_assignee_company_active_updated" ON "Assignee"("company", "updatedAt" DESC) WHERE "deletedAt" IS NULL;
CREATE INDEX IF NOT EXISTS "idx_deployment_company_updated" ON "Deployment"("company", "updatedAt");
CREATE INDEX IF NOT EXISTS "idx_deployment_company_project" ON "Deployment"("company", "project");
CREATE INDEX IF NOT EXISTS "idx_deployment_project_active_date" ON "Deployment"("project", "date" DESC, "createdAt" DESC) WHERE "deletedAt" IS NULL;
CREATE INDEX IF NOT EXISTS "idx_deployment_company_status" ON "Deployment"("company", "status");
CREATE INDEX IF NOT EXISTS "idx_deployment_company_date" ON "Deployment"("company", "date");
CREATE INDEX IF NOT EXISTS "idx_deployment_company_active_date" ON "Deployment"("company", "date" DESC, "createdAt" DESC) WHERE "deletedAt" IS NULL;
CREATE INDEX IF NOT EXISTS "idx_execrun_company_suite" ON "ExecutionRun"("company", "testSuiteId");
CREATE INDEX IF NOT EXISTS "idx_execrun_company_status" ON "ExecutionRun"("company", "status");
CREATE INDEX IF NOT EXISTS "idx_execrun_suite_number" ON "ExecutionRun"("testSuiteId", "runNumber" DESC);
CREATE INDEX IF NOT EXISTS "idx_execrun_company_active" ON "ExecutionRun"("company", "startedAt" DESC) WHERE "deletedAt" IS NULL;
CREATE INDEX IF NOT EXISTS "idx_caseverdict_run" ON "CaseVerdict"("executionRunId");
CREATE INDEX IF NOT EXISTS "idx_caseverdict_company_run" ON "CaseVerdict"("company", "executionRunId");
CREATE INDEX IF NOT EXISTS "idx_caseverdict_testcase" ON "CaseVerdict"("testCaseId");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_caseverdict_run_case" ON "CaseVerdict"("executionRunId", "testCaseId");
CREATE INDEX IF NOT EXISTS "idx_dashcomment_company_entity" ON "DashboardComment"("company", "entityType", "entityId");
CREATE INDEX IF NOT EXISTS "idx_dashcomment_company_created" ON "DashboardComment"("company", "createdAt");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_presence_user" ON "PresenceHeartbeat"("userId");
CREATE INDEX IF NOT EXISTS "idx_presence_company_lastseen" ON "PresenceHeartbeat"("company", "lastSeen");
CREATE INDEX IF NOT EXISTS "idx_dashfilter_company_user" ON "DashboardFilter"("company", "userId");
CREATE INDEX IF NOT EXISTS "idx_dashfilter_company_shared" ON "DashboardFilter"("company", "shared");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_dashfilter_unique_name" ON "DashboardFilter"("company", "userId", "name") WHERE "deletedAt" IS NULL;
CREATE INDEX IF NOT EXISTS "idx_worklog_company" ON "WorkLog"("company");
CREATE INDEX IF NOT EXISTS "idx_worklog_company_date" ON "WorkLog"("company", "date");
CREATE INDEX IF NOT EXISTS "idx_worklog_company_assignee" ON "WorkLog"("company", "assignee");
CREATE INDEX IF NOT EXISTS "idx_worklog_company_active_date" ON "WorkLog"("company", "date" DESC) WHERE "deletedAt" IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS "idx_company_name" ON "Company"("name");
CREATE INDEX IF NOT EXISTS "idx_company_status" ON "Company"("status");
CREATE INDEX IF NOT EXISTS "idx_company_plan" ON "Company"("plan");
CREATE INDEX IF NOT EXISTS "idx_auditlog_created" ON "AdminAuditLog"("createdAt" DESC);
CREATE INDEX IF NOT EXISTS "idx_auditlog_actor" ON "AdminAuditLog"("actor");
CREATE INDEX IF NOT EXISTS "idx_announcement_active" ON "Announcement"("active");
CREATE INDEX IF NOT EXISTS "idx_announcement_target" ON "Announcement"("targetCompany");
CREATE INDEX IF NOT EXISTS "idx_supportticket_company" ON "SupportTicket"("company");
CREATE INDEX IF NOT EXISTS "idx_supportticket_status" ON "SupportTicket"("status");
CREATE INDEX IF NOT EXISTS "idx_supportticket_company_status" ON "SupportTicket"("company", "status");
CREATE INDEX IF NOT EXISTS "idx_collabpresence_module_item" ON "CollaborationPresence"("module", "itemId");
CREATE INDEX IF NOT EXISTS "idx_collabpresence_company_module" ON "CollaborationPresence"("company", "module");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_collabpresence_user_module_item" ON "CollaborationPresence"("userId", "module", "itemId");
CREATE INDEX IF NOT EXISTS "idx_adminnotif_read" ON "AdminNotification"("read");
CREATE INDEX IF NOT EXISTS "idx_adminnotif_created" ON "AdminNotification"("createdAt" DESC);
CREATE INDEX IF NOT EXISTS "idx_moduleview_company_module" ON "ModuleView"("company", "module");
CREATE INDEX IF NOT EXISTS "idx_moduleview_company_user_module" ON "ModuleView"("company", "userId", "module");
CREATE INDEX IF NOT EXISTS "idx_moduleview_company_shared" ON "ModuleView"("company", "shared");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_notifpref_user" ON "NotificationPreference"("userId");
CREATE INDEX IF NOT EXISTS "idx_notifpref_company" ON "NotificationPreference"("company");
`;
